name: GemMod
version: '1.0'
main: me.honeyberries.gemMod.GemMod
api-version: '1.21.5'
authors: [ HoneyBerries ]
description: Plugin for the Gem SMP
softdepend: [packetevents]
folia-supported: true
commands:
  gem:
    description: Lets you give players gems
    usage: /gem <gem-type> <player (optional)> <amount (optional)>
    permission: gemmod.command.gem
    permission-message: You do not have permission to use this command.

permissions:
    gemmod.command.gem:
        description: Allows the player to use the /gem command
        default: op
    gemmod.cooldown.bypass:
      description: Allows the player to bypass cooldowns
      default: false
